-- ============================================================
-- SmartSec Database Schema — Run this in Supabase SQL Editor
-- ============================================================
-- How to run:
--   1. Go to https://supabase.com → Your SmartSec project
--   2. Click "SQL Editor" in the left sidebar
--   3. Paste this entire file and click "Run"
-- ============================================================


-- ============================================================
-- TABLE 1: users
-- Stores registered user accounts and their security profile.
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username        VARCHAR(30) UNIQUE NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    
    -- Security profile
    risk_score      FLOAT DEFAULT 0.0,
    risk_level      VARCHAR(10) DEFAULT 'Low',     -- 'Low', 'Medium', 'High'
    
    -- Login tracking
    last_login_at   TIMESTAMPTZ,
    last_login_ip   VARCHAR(45),                    -- IPv4 or IPv6
    login_count     INTEGER DEFAULT 0,
    failed_attempts INTEGER DEFAULT 0,
    
    -- Metadata
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- TABLE 2: login_events
-- Every login attempt (success or failure) is logged here.
-- This feeds into the IDS anomaly detection module.
-- ============================================================
CREATE TABLE IF NOT EXISTS login_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID REFERENCES users(id) ON DELETE CASCADE,
    
    -- Event details
    event_type      VARCHAR(20) NOT NULL,           -- 'SUCCESS', 'FAILURE', 'SUSPICIOUS'
    ip_address      VARCHAR(45),
    location        VARCHAR(100),                   -- City, Country (simulated)
    user_agent      TEXT,
    
    -- Risk assessment at time of login
    risk_score      FLOAT DEFAULT 0.0,
    risk_flags      TEXT[],                         -- Array of flag strings e.g. ['UNUSUAL_TIME', 'NEW_IP']
    
    created_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- TABLE 3: alerts
-- Security alerts generated by the IDS and other modules.
-- Shown on the central dashboard.
-- ============================================================
CREATE TABLE IF NOT EXISTS alerts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID REFERENCES users(id) ON DELETE CASCADE,
    
    -- Alert details
    alert_type      VARCHAR(50) NOT NULL,           -- 'SUSPICIOUS_LOGIN', 'ANOMALY', 'PHISHING_DETECTED'
    severity        VARCHAR(10) NOT NULL,           -- 'Low', 'Medium', 'High'
    message         TEXT NOT NULL,
    
    -- Status
    is_read         BOOLEAN DEFAULT FALSE,
    resolved        BOOLEAN DEFAULT FALSE,
    
    created_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- TABLE 4: url_scans
-- Results from the phishing URL detection module.
-- ============================================================
CREATE TABLE IF NOT EXISTS url_scans (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID REFERENCES users(id) ON DELETE CASCADE,
    
    -- Scan details
    url             TEXT NOT NULL,
    verdict         VARCHAR(20) NOT NULL,           -- 'Safe', 'Suspicious', 'Phishing'
    confidence      FLOAT NOT NULL,                 -- 0.0 to 1.0
    risk_score      FLOAT NOT NULL,                 -- 0 to 100
    
    -- Feature breakdown (stored as JSON)
    features        JSONB,
    
    created_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- TABLE 5: user_activity
-- Tracks all user actions for the IDS module.
-- Used to detect behavioral anomalies.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_activity (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID REFERENCES users(id) ON DELETE CASCADE,
    
    -- Activity details
    action          VARCHAR(100) NOT NULL,          -- e.g., 'scan_url', 'view_dashboard', 'api_call'
    endpoint        VARCHAR(200),                   -- Which API endpoint was called
    method          VARCHAR(10),                    -- GET, POST, etc.
    status_code     INTEGER,                        -- HTTP response code
    response_time   FLOAT,                          -- In milliseconds
    
    -- Anomaly detection
    is_anomaly      BOOLEAN DEFAULT FALSE,
    anomaly_score   FLOAT DEFAULT 0.0,
    
    created_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- INDEXES — Speed up common queries
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_login_events_user_id   ON login_events(user_id);
CREATE INDEX IF NOT EXISTS idx_login_events_created   ON login_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_user_id         ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_created         ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_url_scans_user_id      ON url_scans(user_id);
CREATE INDEX IF NOT EXISTS idx_user_activity_user_id  ON user_activity(user_id);
CREATE INDEX IF NOT EXISTS idx_user_activity_created  ON user_activity(created_at DESC);


-- ============================================================
-- AUTO-UPDATE updated_at on users table
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- Verify tables were created
-- ============================================================
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
